<?php
include 'functions.php'; ?>
<!DOCTYPE HTML>
<html lang="en-US">
    <head>
		<meta charset="UTF-8">
		<meta http-equiv="x-ua-compatible" content="ie=edge">
		<title>Kullanıcı Sözleşmesi - Showmarket</title>
		<meta name="description" content="">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<!-- Favicon Icon -->
        <link rel="icon"  type="image/png" href="assets/images/favicon.png">		
        <link rel="stylesheet" type="text/css" href="assets/css/bootstrap.min.css"/>
        <link rel="stylesheet" type="text/css" href="venobox/venobox.css"/>
        <link rel="stylesheet" type="text/css" href="assets/css/plugin_theme_css.css"/>
        <link rel="stylesheet" type="text/css" href="assets/css/style.css"/>        
		<link rel="stylesheet" type="text/css" href="style.css"/>
		<link rel="stylesheet" type="text/css" href="assets/css/responsive.css"/>
		<!-- modernizr js -->	
        <script src="assets/js/vendor/modernizr-2.8.3.min.js"></script>		
		
    </head>
<body>

<?php include 'header.php' ?>


<!-- breadcumb-area	 -->
<div class="breadcumb-area">
	<div class="container">				
		<div class="row">
			<div class="col-md-12 txtc  text-center ccase">
				<div class="brpt">
					<h2>Kullanıcı Sözleşmesi</h2>
				</div>
				<div class="breadcumb-inner">
					<ul>
						<li><a href="https://eboshowmarket.com/">Anasayfa</a></li>
						<li><i class="fas fa-angle-right"></i></li>
						<li>Kullanıcı Sözleşmesi</li>
					</ul>						
				</div>
			</div>
		</div>
	</div>
</div>




<div class="solutech_about_area choose">
	<div class="container">	
		<div class="row about">
			<div class="col-md-12 col-sm-12">
				<div class="witr_section_title">
					<div class="witr_section_title_inner text-left">
					<p>KULLANICI S&Ouml;ZLEŞMESİ</p>
<p>Madde 1<br />Giriş</p>
<p>1.1. İşbu kullanıcı s&ouml;zleşmesi ve Web Sitesi&rsquo;nde yer alan diğer kurallar &ldquo;uzmanıbaksın.com&rdquo; ve &ldquo;uzmanı baksın&rdquo; mobil uygulaması tarafından sunulan hizmetlere ilişkin şart ve koşulları ve Web Sitesi&rsquo;nin kullanılmasına ilişkin kuralları d&uuml;zenlemektedir. Kullanıcı&rsquo;nın, Web Sitesi &uuml;zerinden &ldquo;Hizmet Talebi&rdquo; veya &ldquo;Hizmet Profili&rdquo; oluştururken işbu S&ouml;zleşmeyi onayladığı veya Web Sitesi&rsquo;nden yararlanmaya başladığı andan itibaren işbu S&ouml;zleşmeye uymayı taahh&uuml;t ettiği kabul edilir. Koşulların sizin i&ccedil;in uygun olmaması halinde l&uuml;tfen Web Sitesi&rsquo;ni ve sunulan hizmetleri kullanmayınız.</p>
<p>1.2. uzmanı baksın, aracılık hizmetlerinin s&uuml;rekliliğini sağlama, ileride doğacak teknik zorunluluklar veya mevzuata uyum sağlanması amacıyla S&ouml;zleşme&rsquo;yi Kullanıcılar aleyhine olmayacak şekilde tek taraflı olarak değiştirme hakkına sahiptir.</p>
<p>Madde 2<br />Tanımlar</p>
<p>İşbu S&ouml;zleşme metni i&ccedil;erisinde;</p>
<p>2.1. &ldquo;uzmanı baksın&rdquo; Ad Soyad (TC: xxxxxxxxxxx)&rsquo;na ait &ldquo;xxxxxxxxxx&rdquo; isimli Adi Şirketi,</p>
<p>2.2. &ldquo;Web Sitesi&rdquo; https://uzmanıbaksın.com internet sitesini ve IOS/Android tabanlı Mobil Uygulamaları,</p>
<p>2.3. &ldquo;Kullanıcı&rdquo; Herhangi bir sebeple Web Sitesi&rsquo;ni kullanan kişileri,</p>
<p>2.4. &ldquo;&Uuml;ye&rdquo; E-posta ve/veya telefon kaydı alınarak işbu Kullanıcı S&ouml;zleşmesi&rsquo;nin kabul edilmesi koşuluna bağlı olarak kendisine kullanıcı adı ve şifre belirleyen Kullanıcı&rsquo;yı,</p>
<p>2.5. &ldquo;Hizmet Alan&rdquo; Web Sitesi &uuml;zerinden Hizmet Verenlerce sunulan herhangi bir hizmeti satın almak i&ccedil;in Hizmet Talebi g&ouml;nderen ger&ccedil;ek veya t&uuml;zel kişi Kullanıcı&rsquo;yı,</p>
<p>2.6. &ldquo;Hizmet Veren&rdquo; (Hizmet Sağlayıcı) Hizmet sağlamak &uuml;zere Web Sitesi &uuml;zerinden Hizmet Profili oluşturan ve işbu Kullanıcı s&ouml;zleşmesini onaylayan şahıs, kuruluş veya t&uuml;zel kişiyi (Hizmet Veren t&uuml;zel bir kişi ise, s&ouml;z konusu tanım Hizmet Veren adına hizmetleri y&uuml;r&uuml;ten ve ona bağlı olarak &ccedil;alışan kişileri de kapsar.),</p>
<p>2.7. &ldquo;Hizmet Talebi&rdquo; Hizmet Alan tarafından, bir veya daha fazla Hizmet Veren&rsquo;den Teklif almak amacıyla Web Sitesi &uuml;zerinde oluşturulan hizmet talebi,</p>
<p>2.8. &ldquo;Teklif&rdquo; Hizmet Veren'in, Hizmet Alan&rsquo;ın g&ouml;nderdiği Hizmet Talebi&rsquo;ne yanıt olarak g&ouml;nderdiği, hizmetleri belli bir s&uuml;re ve belli bir &uuml;cret karşılığında sağlama teklifini,</p>
<p>2.9. &ldquo;Teklif Modeli&rdquo; Hizmet Alan&rsquo;ın hizmet talebini oluşturduktan sonra, bu talebin Hizmet Verenlere y&ouml;nlendirilmesiyle Hizmet Verenlerin kendi inisiyatifleri doğrultusunda Hizmet Alan&rsquo;a Teklif verdiği modeli,</p>
<p>2.10. &ldquo;Rezervasyon Modeli&rdquo; Hizmet Alan&rsquo;ın Hizmet Talebi oluştururken tek seferlik veya d&uuml;zenli olarak talep edeceği hizmete ilişkin g&uuml;n ve saat belirlediği ve Hizmet Veren&rsquo;in uzmanı baksın tarafından y&ouml;nlendirildiği modeli,</p>
<p>2.10.1. &ldquo;D&uuml;zenli Hizmet&rdquo; Rezervasyon Modeli&rsquo;nde Hizmet Alan&rsquo;ın haftalık veya 2 haftada 1 gibi sıklık belirten se&ccedil;eneklerden birini se&ccedil;mesi durumunda se&ccedil;tiği sıklığa g&ouml;re Hizmetin otomatik yenilenmesiyle oluşan modeli,</p>
<p>2.10.2. &ldquo;Abonelik Sistemi&rdquo; Rezervasyon Modeli&rsquo;nin bir par&ccedil;ası olup daha uygun fiyatlar karşılığında Hizmet Alan&rsquo;ın belirtilen s&uuml;re boyunca d&uuml;zenli olarak hizmet alacağını taahh&uuml;t ettiği sistemi,</p>
<p>2.10.3. &ldquo;Cayma bedeli&rdquo; Rezervasyon Modeli&rsquo;nde Hizmet Alan&rsquo;ın almayı taahh&uuml;t ettiği hizmetlerinden tamamlayamadığı hizmetlerin toplam &uuml;creti ya da o ana kadar abonelik kapsamında alınmış hizmetlerin taahh&uuml;ts&uuml;z fiyat farkının toplamı se&ccedil;eneklerinden tutar olarak en d&uuml;ş&uuml;k olanı,</p>
<p>2.10.4. &ldquo;İş Kabul Etme&rdquo; Rezervasyon Modeli&rsquo;nde Hizmet Veren&rsquo;in işi &uuml;stlenmesi ve Rezervasyon dahilinde belirtilen g&uuml;n ve saatte detaylarda belirtilen hizmeti ger&ccedil;ekleştireceğini taahh&uuml;t etmesi,</p>
<p>2.10.5. &ldquo;İş Silme&rdquo; Rezervasyon Modeli&rsquo;nde Hizmet Veren&rsquo;in kabul ettiği herhangi bir işe gidemeyeceğini mazeret g&ouml;stererek Web Sitesi &uuml;zerinden bildirmesi,</p>
<p>2.11. &ldquo;Hizmet Profili&rdquo; Hizmet Veren&rsquo;in Hizmet Alan&rsquo;a sunabileceği hizmetin tanıtımını yapmak, Teklif Modeli&rsquo;nde Hizmet Alanlar tarafından sunulan Hizmet Talebi&rsquo;ne Teklif vermek amacıyla, Rezervasyon Modeli&rsquo;nde Hizmet Alanlar tarafından yapılan rezervasyonları kabul etmek i&ccedil;in Web Sitesi &uuml;zerinde oluşturduğu profili,</p>
<p>2.12. &ldquo;Teklif Verme &Uuml;creti&rdquo; Teklif Modeli&rsquo;nde Hizmet Veren&rsquo;in Hizmet Alan&rsquo;a Teklif verme hakkını kazanabilmesi i&ccedil;in uzmanı baksın&rsquo;e &ouml;deyeceği hizmet bedelini,</p>
<p>2.13. &ldquo;Komisyon &Uuml;creti&rdquo; Anlaşmaya Varılmış İşler i&ccedil;in Teklif Modeli&rsquo;nde uzmanı baksın tarafından belirlenen oranda Anlaşmaya Varılmış Teklif &uuml;zerinden hak ettiği bedeli, Rezervasyon Modeli&rsquo;nde ise Sabit Fiyat &uuml;zerinden uzmanı baksın&rsquo;in hak ettiği bedeli,</p>
<p>2.14. &ldquo;Sabit Fiyat&rdquo; Rezervasyon Modeli&rsquo;nde Hizmet Alan tarafından Online &Ouml;deme Sistemi aracılığıyla Hizmet Veren&rsquo;e &ouml;denecek olan ve uzmanı baksın&rsquo;in Komisyon &Uuml;creti&rsquo;ni de i&ccedil;eren, Web Sitesi &uuml;zerinden hizmet i&ccedil;in &ouml;nceden a&ccedil;ıklanan standart birim bedeli,</p>
<p>2.15. &ldquo;Hizmet Bedeli&rdquo; Teklif Modeli&rsquo;nde Hizmet Alan&rsquo;ın Hizmet Talebi doğrultusunda Hizmet Verenlerin Web Sitesi &uuml;zerinden verdiği teklifler arasından anlaştığı teklifin bedeli, Rezervasyon Modeli&rsquo;nde ise Hizmet Alan&rsquo;ın Hizmet Talebi doğrultusunda verilen Hizmet karşılığında &ouml;demekle y&uuml;k&uuml;ml&uuml; olduğu bedeli,</p>
<p>2.16. &ldquo;Anlaşmaya Varılmış İş&rdquo; Teklif Modeli&rsquo;nde Hizmet Verenler tarafından Web Sitesi &Uuml;zerinden g&ouml;nderilen Teklif&rsquo;in Hizmet Alan tarafından Web Sitesi &Uuml;zerinden kabul edilmesi ya da Hizmet Veren&rsquo;in Hizmet Alan ile anlaşmaya vardıktan sonra bunu Web Sitesi &uuml;zerinden belirtmesi, Rezervasyon Modeli&rsquo;ndeki hizmetler i&ccedil;in Hizmet Talebi&rsquo;nin Hizmet Alan tarafından onaylanması,</p>
<p>2.17. &ldquo;Online &Ouml;deme Sistemi&rdquo; Rezervasyon Modeli&rsquo;nde Hizmet Alan&rsquo;ın Web Sitesi &uuml;zerinden alacağı hizmete ilişkin &uuml;cretin, uzmanı baksın ya da uzmanı baksın&rsquo;in iş birliği yaptığı &ouml;deme kuruluşları tarafından, işbu S&ouml;zleşme&rsquo;de belirlenen h&uuml;k&uuml;m ve koşullar altında kredi kartı, banka kartı, bankalar tarafından sağlanan online &ouml;demeyi destekleyen sair &ouml;deme y&ouml;ntemleriyle Hizmet Alan&rsquo;dan tahsilini sağlayan sistemi, Teklif Modeli&rsquo;nde ise Hizmet Alan&rsquo;ın g&ouml;nderdiği Hizmet Talebi&rsquo;ne Teklif vermek amacıyla uzmanı baksın&rsquo;e &ouml;dediği Teklif Verme &Uuml;creti ve uzmanı baksıne &ouml;demekle y&uuml;k&uuml;ml&uuml; olduğu Komisyon &Uuml;cretlerinin, uzmanı baksın ve uzmanı baksın&rsquo;in iş birliği yaptığı &ouml;deme kuruluşları tarafından, işbu S&ouml;zleşme&rsquo;de belirlenen h&uuml;k&uuml;m ve koşullar altında kredi kartı, banka kartı, bankalar tarafından sağlanan online &ouml;demeyi destekleyen sair &ouml;deme y&ouml;ntemleriyle Hizmet Veren&rsquo;den tahsilini sağlayan sistemi,</p>
<p>2.18. &ldquo;S&ouml;zleşme&rdquo; İşbu Kullanıcı S&ouml;zleşmesini,</p>
<p>2.19. &ldquo;Y&ouml;netmelik&rdquo; 26 Ağustos 2015 g&uuml;nl&uuml; ve 29457 sayılı Resm&icirc; Gazete&rsquo;de yayınlanan Elektronik Ticarette Hizmet Sağlayıcı ve Aracı Hizmet Sağlayıcılar Hakkında Y&ouml;netmelik&rsquo;i,<br />ifade eder.</p>
<p>Madde 3<br />uzmanı baksın Tarafından Sunulan Hizmetler</p>
<p>3.1. uzmanı baksın, Hizmet Veren ve Hizmet Alan&rsquo;ın i&ccedil;eriklerini kendileri oluşturdukları hizmet, &uuml;r&uuml;n veya hizmet talebi bilgilerinin, kendisine bildirilen i&ccedil;eriğe uygun olarak ve işbu S&ouml;zleşme h&uuml;k&uuml;mleri &ccedil;er&ccedil;evesinde, Web Sitesi&rsquo;nde yer almasını sağlar.</p>
<p>3.2. uzmanı baksın, yalnızca bir platformdur, Web Sitesi&rsquo;nde yer alan hizmetlerin sahibi veya sağlayıcısı değildir. Y&ouml;netmelik&rsquo;in 6/4 maddesine g&ouml;re, uzmanı baksın aracı hizmet sağlayıcıdır ve hizmet sunduğu elektronik ortamı kullanan ger&ccedil;ek ve t&uuml;zel kişiler tarafından sağlanan i&ccedil;eriği kontrol etmek, bu i&ccedil;erik ve i&ccedil;eriğe konu mal veya hizmetle ilgili hukuka aykırı bir faaliyetin ya da durumun s&ouml;z konusu olup olmadığını araştırmakla y&uuml;k&uuml;ml&uuml; değildir.</p>
<p>KULLANIM ŞARTLARI</p>
<p>Madde 4<br />&Uuml;yelik Sistemi</p>
<p>4.1. Web Sitesi&rsquo;ne &uuml;yelik &uuml;cretsizdir. &Uuml;yeler, tek bir &Uuml;ye hesabı &uuml;zerinden aynı anda birden fazla Hizmet Talebi g&ouml;nderebilirler. Şifre'nin belirlenmesi ve korunması &uuml;yenin kendi sorumluluğundadır. Kullanıcı adı ve şifresi paylaşılmamalı ve &ouml;zenle korunmalıdır. &Uuml;ye, hesabının kendi kusuru nedeniyle başka kişiler tarafından k&ouml;t&uuml; niyetle kullanılmasından doğrudan sorumludur. uzmanı baksın, bu sebeple &ouml;demek zorunda kalacağı her t&uuml;rl&uuml; adli/idari para cezası ve/veya tazminat i&ccedil;in &Uuml;ye&rsquo;ye aynen r&uuml;cu hakkına sahiptir.</p>
<p>4.2. &Uuml;ye hesabı oluştururken Web Sitesi&rsquo;ne beyan edilen isim, adres, telefon, e-posta, vergi dairesi, gibi her t&uuml;rl&uuml; bilgi, g&uuml;ncel, doğru ve eksiksiz olmalıdır. S&ouml;z konusu bilgilerin yanlış veya eksik olması nedeniyle &Uuml;yelerin veya 3. kişilerin uğrayacağı zararlardan sorumluluk ilgili &Uuml;ye&rsquo;ye aittir.</p>
<p>4.3. &Uuml;yeliğe ilişkin kullanım hakları, kullanıcı adı ve şifresi başkalarına devredilemez.</p>
<p>4.4. Eğer Hizmet Veren&rsquo;in veya Hizmet Alan&rsquo;ın uzmanı baksın&rsquo;e &ouml;demesi gereken tutar bulunuyorsa bu tutarı &ouml;demeden hesabı silinemez.</p>
<p>Madde 5<br />Hizmet Talebi Oluşturulması</p>
<p>5.1. En az 18 yaşında olan ve temyiz kudretini haiz herhangi bir Kullanıcı, işbu S&ouml;zleşme koşulları uyarınca kayıt formunda talep edilen bilgileri doğru ve eksiksiz olarak doldurarak bir Hizmet Talebi oluşturabilir.</p>
<p>5.2. İşbu s&ouml;zleşmeyi kabul eden kullanıcılar 18 yaşından b&uuml;y&uuml;k olduklarını beyan ve kabul etmiş sayılırlar. Hizmet Talebi&rsquo;nde bu beyanın aksinden doğabilecek durumlardan uzmanı baksın&rsquo;in sorumlu tutulamayacağını ve kendi sorumluluklarında olduğunu kabul ve beyan ederler.</p>
<p>5.3. Ge&ccedil;erli bir Hizmet Talebi oluşturmak i&ccedil;in hizmete ilişkin gerekli bilgilerin (talep edilen işin niteliği, &ouml;zelliği, kalitesi, ifa ve teslim yeri ve işin s&uuml;resi vb.) eksiksiz, doğru ve a&ccedil;ık olarak verilmesi ve i&ccedil;eriğinin işbu S&ouml;zleşme&rsquo;de belirtilen şartlara uygun olması gerekir.</p>
<p>5.4. uzmanı baksın, Hizmet Talebini kendi teknolojisini kullanarak denetiminden ge&ccedil;irdikten sonra, uygun olması halinde yayımlar. Ancak Hizmet Talebi&rsquo;nin i&ccedil;eriğine ilişkin t&uuml;m sorumluluk Hizmet Alan&rsquo;a aittir.</p>
<p>5.5. Etik ve ahlaki değerlere uygun olmayan talep i&ccedil;erikleri oluşturulmamalı, bu tip i&ccedil;erikli taleplere teklif verilmemelidir. Bu t&uuml;r talepleri oluşturma ya da bu t&uuml;r taleplere teklif verme sebebiyle doğacak t&uuml;m sorumluluk talep sahibi Hizmet Alan'a ve/veya teklif veren Hizmet Veren'e aittir.</p>
<p>Madde 6<br />Teklif Modeli</p>
<p>6.1. Hizmet Veren, kendisine g&ouml;nderilen bir Hizmet Talebi i&ccedil;in Web Sitesi &uuml;zerinden Teklif vererek, Hizmet Talebi&rsquo;nde belirtilen hizmeti Teklif&rsquo;te belirtilen fiyat &uuml;zerinden yapmayı teklif eder.</p>
<p>6.2. Hizmet Alan ve Hizmet Veren&rsquo;in anlaşmaya varması, Teklif&rsquo;te belirtilen fiyat &uuml;zerinden hizmetin ger&ccedil;ekleşeceği anlamına gelir. Hizmet Veren&rsquo;in ilgili işe ilişkin keşif yapması ve/veya Hizmet, ihtiya&ccedil; ve şartlarında oluşabilecek değişiklikler sebebiyle, Teklif&rsquo;te belirtilen fiyatlar değişkenlik g&ouml;sterebilir, s&ouml;z konusu hallerde Teklif&rsquo;te belirtilen fiyat taraflarca anlaşmaya varılarak Web Sitesi&rsquo;nde g&uuml;ncellenir.</p>
<p>6.3. Verilen Teklifler Hizmet Verenler tarafından belirtilen s&uuml;re boyunca ge&ccedil;erli ve bağlayıcıdır. Hizmet Veren&rsquo;in belirttiği s&uuml;reden &ouml;nce Teklif&rsquo;i geri &ccedil;ekmesinden uzmanı baksın herhangi bir sorumluluğu bulunmamaktadır.</p>
<p>Madde 7<br />Hizmet Verenler i&ccedil;in: Teklif Modeli Değişiklik ve İptal Kuralları</p>
<p>7.1. Anlaşılan bir Teklif&rsquo;e konu olan hizmete ilişkin her t&uuml;rl&uuml; değişiklik Hizmet Alan ile birlikte Hizmet Veren tarafından ortaklaşa olarak Web Sitesi &uuml;zerinde kararlaştırılmalıdır. Web Sitesi&rsquo;nden g&ouml;nderilen bir Hizmet Talebi&rsquo;ne ilişkin olarak uzmanı baksın&rsquo;e bildirilmeksizin, uzmanı baksın&rsquo;e aracılık &uuml;creti &ouml;denmemesi amacıyla tarafların anlaştığı ve teklif verildiği uzmanı baksın tarafından tespit edilirse, uzmanı baksın sağlanan hizmete ilişkin Komisyon bedeline hak kazanır ve ilgili Komisyon &Uuml;creti Hizmet Veren tarafından uzmanı baksın&rsquo;e &ouml;denir.</p>
<p>7.2. uzmanı baksın, teklif verme işlemini Hizmet Verenler i&ccedil;in &uuml;cretli olarak sunabilir, teklif başına veya teklifteki bedel &uuml;zerinden veya farklı bir şekilde Teklif Verme &Uuml;creti alabilir. Hizmet Veren, teklif verdiği hizmetler i&ccedil;in keşif veya ek masraf yapsa bile, teklifinin kabul edilmemesi, teklifinin Hizmet Alan tarafından g&ouml;r&uuml;lmemesi, Hizmet Talebi&rsquo;nin iptal edilmesi veya aynı hizmet i&ccedil;in başka Hizmet Verenlerin de teklif vermiş olması, hi&ccedil;bir şekilde Hizmet Veren&rsquo;e Teklif Verme &Uuml;creti&rsquo;nin iade edilmesi anlamına gelmemektedir.</p>
<p>Madde 8<br />Hizmet Alanlar i&ccedil;in: Teklif Modeli Değişiklik ve İptal Kuralları</p>
<p>8.1. uzmanı baksın, Hizmet Alanlar i&ccedil;in Hizmet Talebi oluşturmayı &uuml;cretsiz olarak sunmaktadır. Hizmet Alan oluşturduğu bir Hizmet Talebi&rsquo;ni Web Sitesi veya mail yoluyla iptal edebilir fakat talebin i&ccedil;eriğinde sonradan bir değişiklik yapması m&uuml;mk&uuml;n değildir.</p>
<p>8.2. Hizmet Alanlar Hizmet Talebi&rsquo;ni iptal etmek isterse, Hizmet Verenlerin ve uzmanı baksın&rsquo;in bir mağduriyet yaşamaması i&ccedil;in bunu Web Sitesi &uuml;zerinden veya mail yoluyla uzmanı baksın&rsquo;e bildirmelidirler.</p>
<p>8.3. Hizmet Alanların Anlaşmaya Varılmış İşleri Web Sitesi &uuml;zerinden iptal etmesi m&uuml;mk&uuml;n değildir, Web Sitesi &uuml;zerinde anlaşılan fakat ger&ccedil;ekleşmeyen işlerin bildirimi uzmanıbaksın@gmail.com mail adresine g&ouml;nderilecek bir e-postayla yapılmalıdır.</p>
<p>8.4. Hizmet Alanların sonradan Hizmet Taleplerini iptal etmesi, uzmanı baksın&rsquo;e bir sorumluluk y&uuml;klemez ve bu konuda doğabilecek y&uuml;k&uuml;ml&uuml;l&uuml;klerden Hizmet Alan sorumludur.</p>
<p>8.5. Hizmet Alanlar uzmanı baksın &uuml;zerinde birden fazla Hizmet Talebi oluşturabilirler. Buna karşın &ccedil;ok fazla sayıda ve arka arkaya ge&ccedil;ersiz Hizmet Talebi oluşturmaları durumunda uzmanı baksın bu kullanıcıları sistemde inaktif duruma getirme yoluyla kullanıcı hesaplarını askıya alma hakkını saklı tutar.</p>
<p>Madde 9<br />Rezervasyon Modeli</p>
<p>9.1 uzmanı baksın, niteliğine g&ouml;re bazı hizmetler i&ccedil;in Hizmet Alan&rsquo;ın belirleyeceği g&uuml;n ve saatlerde uygun olan standart bir tarife &uuml;zerinden d&uuml;zenli veya tek seferlik Hizmet Veren y&ouml;nlendirilmesini &ouml;ng&ouml;ren bir Rezervasyon Modeli sağlar.</p>
<p>9.2. Hizmet Alan Online &Ouml;deme Sistemi aracılığıyla kredi kartı ya da banka kartı bilgilerini girerek Hizmet Talebi&rsquo;ni onaylar. Hizmet Alan, &ouml;demenin rezervasyon yapıldığı anda alınacağını, daha sonra talep edilen d&uuml;zenli hizmetler i&ccedil;in sistem kurallarına g&ouml;re &ouml;demenin randevu tarihinden 1 g&uuml;n &ouml;nce alınacağını bildiğini kabul ve beyan eder.</p>
<p>9.3. Hizmet bedeli alınmasına rağmen, hizmetin ifası Madde 7&rsquo;deki Rezervasyon Modeli İptal Kuralları dahilinde m&uuml;mk&uuml;n olmaz ise, hizmet bedeli banka tarafından kendiliğinden kredi kartına ya da banka kartına iade edilmektedir. Bu durumda, Hizmet Alan&rsquo;ın ayrıca bir iptal prosed&uuml;r&uuml; işletmesine gerek kalmamaktadır.</p>
<p>9.4. Hizmet Alan rezervasyon g&uuml;n&uuml;nden &ouml;nce kendisine y&ouml;nlendirilen Hizmet Veren detaylarını Web Sitesi&rsquo;nde talep detay sayfasından g&ouml;r&uuml;nt&uuml;leyebilir. Hizmet Alan, kendisine y&ouml;nlendirilen Hizmet Veren&rsquo;i kabul etmezse hizmetin verileceği g&uuml;nden &ouml;nce uzmanıbaksın@gmail.com adresine e-posta g&ouml;ndererek Hizmet Veren&rsquo;in değiştirilmesini talep eder. Aksi halde Hizmet Veren kabul edilmiş sayılır.</p>
<p>Madde 10<br />Hizmet Alanlar i&ccedil;in: Rezervasyon Modeli Değişiklik ve İptal Kuralları</p>
<p>10.1. Hizmet Alanlar rezervasyon başlangıcına kadar web sitesi &uuml;zerinden rezervasyon değişikliği yapabilirler. İstisnai durumlarda uzmanı baksın de Hizmet Alan i&ccedil;in, rezervasyon tarih değişikliği yapabilir.</p>
<p>Tarih değişikliği herhangi bir iş i&ccedil;in en fazla 10 defa yapılabilir.</p>
<p>Hizmet Alan rezervasyonun başlamasına 24 saatten az kala ve &uuml;zerinde Hizmet Veren olan bir işi erteleyebilir. Ancak, eğer daha sonradan bu rezervasyonu iptal etmek isterse, o zaman rezervasyon &uuml;creti işin başlamasına ne kadar zaman kalmış şartına bakılmaksızın m&uuml;şteriye iade edilmez ve Madde 10.2&rsquo;ye istinaden rezervasyon iptal &uuml;creti Hizmet Alanın kredi kartından &ccedil;ekilir.</p>
<p>10.2. Hizmet Alanlar rezervasyon başlangıcından 24 saat &ouml;ncesine kadar hi&ccedil;bir ekstra &uuml;cret &ouml;demeden rezervasyonlarını Web Sitesi &uuml;zerinden iptal edebilirler.</p>
<p>İstisnai durumlarda uzmanı baksın, Hizmet Alan i&ccedil;in bir Hizmet Veren eşleştirmemişse, Hizmet Alan 24 saat &ouml;ncesi kuralına bakılmaksızın, iptal etme hakkına sahiptir.</p>
<p>Ancak rezervasyon başlangıcına 24 saatten az kalmış ve işi kabul etmiş bir Hizmet Veren var ise Hizmet Alan rezervasyonu iptal ettiği takdirde Hizmet Bedeli&rsquo;nin iadesi kesinlikle yapılmaz. Hizmet Alan Web Sitesi &uuml;zerinde iptal etmek istediğinde karşısına uyarı ekranı &ccedil;ıkar ve iptal ettiği takdirde ne kadar &ouml;deyeceği belirtilir. Hizmet Alan işleme devam ederek bu miktarı &ouml;deyeceğini kabul eder.</p>
<p>10.3. Hizmet Veren'in işe gitmemesi sebebiyle hem Hizmet Alan hem de uzmanı baksın&rsquo;in mağdur olduğu durumlarda uzmanı baksın&rsquo;in ya da m&uuml;şterinin &uuml;cret ya da tazminat &ouml;deme y&uuml;k&uuml;ml&uuml;l&uuml;ğ&uuml; bulunmamaktadır.</p>
<p>Ancak bu gibi durumlarda Hizmet Alan&rsquo;ın &uuml;cret iadesi alabilmesi i&ccedil;in rezervasyon bitiminden itibaren 24 saat i&ccedil;erisinde uzmanı baksın&rsquo;e haber vermesi gerekmektedir. Daha ge&ccedil; bildirilen durumlarda hizmet alındı kabul edilir ve para iadesi yapılamaz.</p>
<p>10.4. Standart hizmet kapsamına girmeyen işleri uzmanı baksın iptal edebilir, ya da Hizmet Alan&rsquo;a iptal edilmesi doğrultusunda bilgilendirme yapılabilir. Bu işlerin iptal edilmesi durumunda uzmanı baksın&rsquo;ten &uuml;cret talep edilemez.</p>
<p>10.5. Hizmet Alanlar rezervasyon yaparken Abonelik Sistemi dahilinde D&uuml;zenli Hizmet se&ccedil;tikleri takdirde belirttikleri s&uuml;re boyunca dahil olan hizmet sayısını tamamlamayı taahh&uuml;t ederek indirimli fiyatlardan yararlanırlar. Taahh&uuml;t s&uuml;resi ve hizmet sayısı rezervasyon &ouml;ncesi aboneliğin se&ccedil;ildiği sayfada yazılı olarak bulunmaktadır. &Ouml;rneğin, 2 haftada 1 sıklıkla 6 ay abonelik alan bir m&uuml;şteri 10 adet hizmet almayı taahh&uuml;t eder.</p>
<p>Eğer aboneliklerini iptal etmek isterlerse Cayma Bedeli &ouml;derler. Cayma Bedeli, cayma anına kadar aldıkları hizmetlerin &ldquo;taahh&uuml;ts&uuml;z fiyatları ile taahh&uuml;tl&uuml; fiyat farkı toplamı&rdquo; ile &ldquo;taahh&uuml;tleri kapsamında almayı kabul ettikleri kalan hizmetlerin taahh&uuml;tl&uuml; fiyatlarının toplamı&rdquo;ndan daha d&uuml;ş&uuml;k olanıdır. Eğer Hizmet Alan cayma hakkını sıradaki rezervasyonunun başlangıcına 24 saatten az kaldığında kullanmak isterse, o zaman cayma bedeline ek olarak yukarıda belirtilen rezervasyon iptali kuralları doğrultusunda o rezervasyon bedelini de &ouml;demekle y&uuml;k&uuml;ml&uuml;d&uuml;r.</p>
<p>10.6. uzmanı baksın, Hizmet Alan memnuniyetini sağlamak amacıyla bu kurallardaki şartları hafifletme, bahsedilen &uuml;cretleri almama, indirim yapma ya da bu &uuml;cretlerin iadesini yapma hakkını saklı tutar.</p>
<p>10.7. Hizmete ilişkin rezervasyonlarda iptaller, sadece Web Sitesi &uuml;zerinden yapılabilir. Mail atılarak yapılan iptaller dikkate alınmaz ve &uuml;cret iadesi yapılmaz.</p>
<p>Madde 11<br />Hizmet Verenler i&ccedil;in: Rezervasyon Modeli İş Kabul Etme ve İş Silme Kuralları</p>
<p>11.1. Hizmet Verenler kendilerine g&ouml;nderilen iş fırsatları arasından istediklerini se&ccedil;ebilir ve Web Sitesi &uuml;zerinde iş fırsatını onaylayarak işi kabul ederler. İşi kabul eden bir Hizmet Veren belirtilen g&uuml;n ve saatte hizmet yerinde olmayı ve hizmete başlamayı taahh&uuml;t eder. Eğer bu taahh&uuml;d&uuml;n&uuml; uzmanı baksın&rsquo;e haber vermeksizin ve mazeretsiz yerine getirmezse uzmanı baksın Hizmet Veren&rsquo;i sistemden &ccedil;ıkarabilir ve g&ouml;nderdiği fırsat sayısında azaltmaya gidebilir.</p>
<p>11.2. Hizmet Verenler işi kabul ettiklerinde Hizmet Alanın ismini, iletişim bilgilerini, Hizmet Alan&rsquo;ın girdiği adres bilgilerini ve bu adresin harita &uuml;zerindeki yerini g&ouml;r&uuml;nt&uuml;leyebilirler. Bu bilgiler gizlidir ve Hizmet Veren Hizmet Alan&rsquo;ın bilgisi ve izni olmadan bu bilgiyi &uuml;&ccedil;&uuml;nc&uuml; şahıslarla paylaşamaz, dağıtamaz, yayınlayamaz.</p>
<p>11.3. Hizmet Veren Hizmet Alan&rsquo;ın sağlamış olduğu iletişim bilgilerini kullanarak ya da Web Sitesi &uuml;zerinden yazarak iletişime ge&ccedil;ebilir. Hizmet Veren uzmanı baksın platformunu aradan &ccedil;ıkarma ama&ccedil;lı Hizmet Alan&rsquo;la iletişime ge&ccedil;emez. Eğer Hizmet Veren&rsquo;in uzmanı baksın&rsquo;i aradan &ccedil;ıkarmak amacıyla Hizmet Alan&rsquo;la iletişime ge&ccedil;er ve bu tespit edilirse uzmanı baksın Hizmet Veren&rsquo;i sistemden &ccedil;ıkarabilir ve uğranılan zarar kadar tazminat talebinde bulunabilir.</p>
<p>11.4. Hizmet Veren isterse Web Sitesi &uuml;zerinden kabul ettiği işin sayfasına girerek iş bilgilerini silebilir. Bu şekilde o işe gideceğine dair vermiş olduğu taahh&uuml;t ortadan kalkar. Ancak Hizmet Verenler bu bildirimlerini ancak rezervasyonun başlangıcından 24 saat &ouml;ncesine kadar yapabilirler. Eğer Hizmet Veren rezervasyon başlangıcına 24 saatten az kaldığı takdirde kabul ettiği işi silerse uzmanı baksın&rsquo;e bildirimini ge&ccedil; yapmış sayılır ve uzmanı baksın ge&ccedil; yapılan bildirimler sebebiyle Hizmet Veren&rsquo;i sistemden &ccedil;ıkarabilir ve g&ouml;nderdiği iş sayısında azaltmaya gidebilir.</p>
<p>11.5. uzmanı baksın, Hizmet Alandan eğer &ouml;deme alamadıysa, o zaman Hizmet Verene de &ouml;deme yapmama hakkına sahiptir.</p>
<p>11.6. uzmanı baksın, Hizmet Veren&rsquo;e iş i&ccedil;in en fazla Hizmet Alan&rsquo;dan aldığı &uuml;cret kadar &ouml;deme yapabilir. İş iptal politikası kapsamında Hizmet Alan&rsquo;dan iptal &uuml;creti alamadıysa Hizmet Veren&rsquo;e de &ouml;deme yapmama hakkına sahiptir.</p>
<p>Madde 12<br />Hizmet Verenler i&ccedil;in Hizmet Profili Oluşturma</p>
<p>12.1. En az 18 yaşında olan ve temyiz kudretini haiz herhangi bir Kullanıcı kayıt formunda talep edilen bilgileri doğru ve eksiksiz olarak doldurarak işbu Kullanıcı S&ouml;zleşmesi koşullarını onayladıktan sonra kabul edilen koşul ve i&ccedil;eriğe uygun bir Hizmet Profili oluşturup Hizmet Veren (Hizmet Sağlayıcı) sıfatı kazanabilir.</p>
<p>12.2. Hizmet Profili oluşturmak i&ccedil;in isim, marka, unvan, iletişim bilgisi, vergi dairesi, vergi numarası gibi kayıt anında istenen bilgiler eksiksiz ve a&ccedil;ık olarak verilmelidir. Hizmet Profili ile ilgili hizmetleri vermek i&ccedil;in gerekli izne, ruhsata, lisansa (varsa) ve nitelik, deneyim ve kabiliyete sahip olduğunu kanıtlayacak ek belge, ehliyet, diploma, servis yetki belgesi, ticaret sicil belgesi, oda kaydı gibi evrakın ve referansların da girişi yapılmalıdır ve bu belgelerin aslı veya noter onaylı sureti uzmanı baksın tarafından istenildiği takdirde ibraz edilmelidir.</p>
<p>12.3. Y&ouml;netmelik Madde 5/4 gereği,</p>
<p>12.3.1. uzmanı baksın &uuml;zerinden hizmet satışı yapan ve tacir veya esnaf olan hizmet sağlayıcı, şu bilgileri eksiksiz olarak bulundurmak zorundadır: (i) Ticaret unvanı, işletme adı veya tescilli marka adı bilgilerinden en az biri. (ii) Tebligata elverişli KEP adresi. (iii) Esnaflar i&ccedil;in vergi kimlik numarası, tacirler i&ccedil;in MERSİS numarası. (iv) Merkez adresi ve onaylanmış telefon numarasının uzmanı baksın&rsquo;e bulunduğuna ilişkin bilgi.</p>
<p>12.3.2. uzmanı baksın &uuml;zerinden hizmet satışı yapan ve tacir veya esnaf olmayan hizmet sağlayıcı, şu bilgileri eksiksiz olarak bulundurmak zorundadır: (i) Adı ve soyadı. (ii) İkametg&acirc;hının bulunduğu il. (iii) Merkez adresi ve onaylanmış telefon numarasının uzmanı baksın &lsquo;e bulunduğuna ilişkin bilgi.</p>
<p>12.4. Hizmet Veren ile ilgili şartlar ve Hizmet Veren&rsquo;in y&uuml;k&uuml;ml&uuml;l&uuml;kleri, işbu Kullanıcı S&ouml;zleşmesi&rsquo;nde detaylı bir şekilde belirtilmektedir. Hizmet sonucunda vermesi gereken evrak, fatura, fiş dahil ancak bunlarla sınırlı olmaksızın kanuni mevzuat dahilinde sair t&uuml;m evrakı da hizmetin ifası ile birlikte Hizmet Alan&rsquo;a iletmek Hizmet Veren&rsquo;in sorumluluğundadır. uzmanı baksın s&ouml;z konusu belgelerin teminine ilişkin olarak herhangi bir sorumluluğu bulunmamaktadır. Hizmet Veren&rsquo;in kayıtlı olduğu vergi dairesine bildireceği kazan&ccedil; beyanları, kendisinin yasal sorumluluğunda ve y&uuml;k&uuml;ml&uuml;l&uuml;ğ&uuml;ndedir.</p>
<p>Madde 13<br />Hizmet Profili, Hizmet Talebi ve Tekliflerin İ&ccedil;eriği</p>
<p>13.1. Hizmet Profilleri, Hizmet Talepleri ve Teklifler ve taraflarca verilen bilgi, belge ve beyanlar (a) herhangi bir &uuml;&ccedil;&uuml;nc&uuml; kişinin, telif hakkı, patent, marka gibi fikri m&uuml;lkiyet haklarını veya diğer haklarını ihlal etmeyecek; (b) y&uuml;r&uuml;rl&uuml;kteki hi&ccedil;bir kanun veya ikincil mevzuatı (ihracat denetimi, t&uuml;ketici koruma, haksız rekabet veya yanıltıcı reklama ilişkin olanlar vb.) ihlal etmeyecek; (c) genel ahlak ve kamu d&uuml;zenine aykırı, d&uuml;r&uuml;st ve doğru olmayan, aldatıcı, yanıltıcı veya &uuml;&ccedil;&uuml;nc&uuml; kişilerin tecr&uuml;be ve bilgi noksanlıklarını istismar edici, can ve mal g&uuml;venliğini tehlikeye d&uuml;ş&uuml;r&uuml;c&uuml;, kamu sağlığını bozucu, hastaları, yaşlıları, &ccedil;ocukları ve &ouml;z&uuml;rl&uuml;leri istismar edici beyan ve tanıtım ifadeleri i&ccedil;ermeyecek; (d) lisansa, izne veya ruhsata bağlı ifa edilebilen hizmetlerden olup da lisanssız, izinsiz veya ruhsatsız şekilde hizmet sağlanarak diğer lisanslı, izinli veya ruhsatlı kişi ve kurumlarla haksız rekabet yapmayacak, (e) tescilli markaların ve/veya tescilsiz olsa bile marka işaretlerini haksız yere kullanmayacak, hukuka aykırı olarak başka bir firmanın bayisi, distrib&uuml;t&ouml;r&uuml; ve yetkili servisi gibi beyanda bulunmayacak, (f) onur kırıcı, karalayıcı, tehditk&acirc;r veya taciz edici nitelikte olmayacak; (g) m&uuml;stehcen olmayacak veya &ccedil;ocuk pornografisi i&ccedil;ermeyecek ve (h) vir&uuml;s, Truva atı gibi zararlı yazılımları veya herhangi bir sistem, veri veya kişisel bilgiye zarar vermeyi ama&ccedil;layan, zarar veren bilgisayar programcılığı uygulamalarını i&ccedil;ermeyecektir. Aksi halde uzmanı baksın&rsquo;in sorumluluğu bulunmayıp, s&ouml;z konusu sorumluluk ilgili Hizmet Veren&rsquo;e veya Kullanıcı&rsquo;ya aittir. Yapılan uygulamayla ya da meslekle ilgili mevzuata aykırı bir durum olduğu takdirde uzmanı baksın Hizmet Veren profilinde değişiklik yapma, profili silme, eksiklik giderilene kadar askıya alma ve Hizmet Veren&rsquo;in Web Sitesi&rsquo;ne tekrar kaydolmasını engelleme hakkını saklı tutar.</p>
<p>13.2. Hizmet Profilleri, Hizmet Talepleri ve Tekliflere ilişkin her t&uuml;rl&uuml; sorumluluk ilgili Hizmet Veren, Hizmet Alan veya Kullanıcı&rsquo;ya ait olup uzmanı baksın&rsquo;in hi&ccedil;bir sorumluluğu bulunmamaktadır.</p>
<p>Madde 14<br />&Ouml;deme</p>
<p>14.1. Online &Ouml;deme Sistemi&rsquo;ne uzmanı baksın&rsquo;in iş birliği yaptığı &ouml;deme kuruluşunun aracı olduğu hallerde; &ouml;deme kuruluşu ile Hizmet Alan ve Hizmet Veren arasındaki ilişki uzmanı baksın&rsquo;ten bağımsız olup ilgili mevzuat gereği &ouml;ng&ouml;r&uuml;len y&uuml;k&uuml;ml&uuml;l&uuml;klerin yerine getirilmesi ve sorumluluk ilgili &ouml;deme kuruluşuna aittir.</p>
<p>14.2. uzmanı baksın&rsquo;in, Online &Ouml;deme Sistemi ile &ouml;demesi yapılan hizmetlerin ilgili Hizmet Alan&rsquo;a eksik veya kusurlu ifası, Hizmet Talebi&rsquo;ne uygun Hizmet Veren bulunamaması veya hizmetin iptali halinde ilgili tutarın Hizmet Veren&rsquo;e iletilmemesi i&ccedil;in &ouml;deme kuruluşuna talimat verme ve/veya ilgili Hizmet Talebini iptal etmek hakkı saklıdır.</p>
<p>14.3. Online &Ouml;deme Sistemi i&ccedil;in &ouml;deme kuruluşları ile anlaşıldığı takdirde uzmanı baksın yalnızca ilgili bedellerin &ouml;denmesi/iadesi i&ccedil;in ilgili kuruluşa gerekli talimatları iletmekle y&uuml;k&uuml;ml&uuml;d&uuml;r. İlgili &ouml;deme kuruluşu tarafından Kullanıcı bilgisi ve gerekli diğer t&uuml;m bilgilerin saklanması ve g&uuml;venli bir şekilde tutulması ve yapılan işlemlerin g&uuml;venli bir şekilde ger&ccedil;ekleştirilmesi ilgili &ouml;deme kuruluşunun y&uuml;k&uuml;ml&uuml;l&uuml;ğ&uuml;ndedir.</p>
<p>14.4. İşbu kullanıcı s&ouml;zleşmesinde tanımlanan sistemin işleyişini sağlamak amacıyla Rezervasyon Modeli&rsquo;nde hizmeti ifa eden Hizmet Veren, uzmanı baksın&rsquo;te sunduğu hizmetlere ilişkin bedellerin kendi nam ve hesabına Hizmet Alan&rsquo;dan tahsil edilmesi konusuna m&uuml;nhasır olarak, uzmanı baksın&rsquo;i temsilci olarak atamaktadır. Hizmet Alan, hizmetlere ilişkin &ouml;demeyi Hizmet Veren&rsquo;in temsilcisi sıfatıyla uzmanı baksın&rsquo;e yapmakla hizmet akdi kapsamında &ouml;deme y&uuml;k&uuml;ml&uuml;l&uuml;ğ&uuml;n&uuml; ifa edecektir. Bu maddede belirtilen temsil yetkisinin Hizmet Veren tarafından verilmemesi veya sonradan iptal edilmesi halinde uzmanı baksın kullanıcı s&ouml;zleşmesini feshetme ve Hizmet Veren&rsquo;in &uuml;yeliğini iptal etme hakkına sahiptir.</p>
<p>Madde 15<br />Teklif Modelinde &Ouml;deme</p>
<p>15.1. Hizmet Talep Eden Alıcı Kullanıcı ve Hizmet Sahibi Satıcı Kullanıcı, uzmanı baksın&rsquo;in veya &Ouml;deme Hizmet Sağlayıcı aracılığıyla verilen yetki doğrultusunda temsilci uzmanı baksın olarak tahsilat s&uuml;recini y&ouml;neteceğini, Hizmet bedelinin Hizmet Sahibi Kullanıcı adına uzmanı baksın tarafından tahsil edileceğini, Hizmet&rsquo;in taahh&uuml;t edildiği şekilde g&ouml;nderilmesi ve iade koşullarının meydana gelmemesi halinde &uuml;r&uuml;n bedelinin Hizmet Talep Eden Kullanıcı adına, Hizmet Sahibi Kullanıcı&rsquo;ya g&ouml;nderileceğini kabul ve beyan ederler. Hizmet Sahibi Kullanıcı; Hizmet Talep Eden Kullanıcı&rsquo;nın, Hizmet bedelini uzmanı baksın&rsquo;e &ouml;demekle, &ouml;deme borcunu ifa etmiş olduğunu ve kendisine ayrıca bir &ouml;demede bulunma zorunluluğu olmadığını kabul ve beyan eder.</p>
<p>15.2. Online &Ouml;deme Sistemi kullanıldığında hizmet karşılığı fiş/fatura veya d&uuml;zenlenmesi gerekli diğer belgeler, ilgili mevzuat gereği d&uuml;zenleme y&uuml;k&uuml;ml&uuml;l&uuml;kleri bulunuyorsa ilgili Hizmet Veren tarafından d&uuml;zenlenir. S&ouml;z konusu hizmete ilişkin fatura/fiş veya diğer belgeler uzmanı baksın&rsquo;ten talep edilemeyecek olup uzmanı baksın yalnızca kendi verdiği hizmetlere ilişkin olarak Komisyon Bedeli ve Teklif Verme &Uuml;creti i&ccedil;in Hizmet Veren&rsquo;lere fatura kesmekle y&uuml;k&uuml;ml&uuml;d&uuml;r.</p>
<p>Madde 16<br />Rezervasyon Modeli&rsquo;nde &Ouml;deme</p>
<p>16.1. Hizmet Alanlar, Online &Ouml;deme Sistemi&rsquo;ni kullanarak banka kartı, kredi kartı veya benzer bir &ouml;deme aracı ile anında online &ouml;deme yaparlar. Online &Ouml;deme Sistemi ile &ouml;deme yapılan durumlarda, kartın hamili haricinde bir başkası tarafından hukuka aykırı şekilde kullanılması halinde 23.02.2006 tarihli 5464 sayılı Banka Kartları ve Kredi Kartları Kanunu ve 10.03.2007 tarihli ve 26458 sayılı Resmi Gazete&rsquo;de yayımlanan Banka Kartları ve Kredi Kartları Hakkında Y&ouml;netmelik h&uuml;k&uuml;mlerine g&ouml;re işlem yapılır.</p>
<p>16.2. Hizmet Alanlar tarafından talep edildiği takdirde Madde 10&rsquo;da belirtilen değişiklik ve iptal kuralları dahilinde uzmanı baksın &uuml;cret iadesi yapabilir veya yapılması i&ccedil;in anlaşmalı &ouml;deme kuruluşuna talimat verebilir.</p>
<p>16.3. uzmanı baksın, Hizmet Veren&rsquo;e iş i&ccedil;in en fazla Hizmet Alan&rsquo;dan aldığı &uuml;cret kadar &ouml;deme yapabilir. uzmanı baksın iş iptal politikası kapsamında Hizmet Alan&rsquo;dan iptal &uuml;creti alamaması durumunda Hizmet Veren&rsquo;e de &ouml;deme yapmama hakkına sahiptir.</p>
<p>16.4. uzmanı baksın&rsquo;in, Online &Ouml;deme Sistemi ile &ouml;demesi yapılan hizmetlerin ilgili Hizmet Alan&rsquo;a eksik veya kusurlu ifası, Hizmet Talebi&rsquo;ne uygun Hizmet Veren bulunamaması veya hizmetin iptali halinde ilgili tutarın Hizmet Veren&rsquo;e iletilmemesi i&ccedil;in &ouml;deme kuruluşuna talimat verme ve/veya ilgili Hizmet Talebini iptal etmek hakkı saklıdır.</p>
<p>16.5. Hizmet Alan, Rezervasyon Modeli&rsquo;nde uzmanı baksın&rsquo;e &ouml;demekle y&uuml;k&uuml;ml&uuml; olduğu iptal veya rezervasyon &uuml;cretlerini &ouml;demelidir. Eğer Hizmet Alan, uzmanı baksın&rsquo;e &ouml;demekle y&uuml;k&uuml;ml&uuml; olduğu &ouml;demeleri yapmaz ise, uzmanı baksın Hizmet Alanın hesabını kullanımını kısıtlayabilir ve uzmanı baksın &ouml;demesi gereken tutarı &ouml;deyene kadar yeni bir &ouml;n &ouml;demeli rezervasyon talebi oluşturmasını engelleyebilir. Hizmet Alan tekrar rezervasyon oluşturmak istediğinde daha &ouml;nce uzmanı baksın &ouml;demesi gereken tutarı da &ouml;deyerek rezervasyonunu oluşturabilir.</p>
<p>Madde 17<br />Hizmet Bedeli İadesi / Cayma Hakkının Kullanılması</p>
<p>17.1. Teklif Modeli&rsquo;nde Hizmet Alan, hizmetin ifa edilmemiş olması ve hizmete başlanmamış olması şartıyla, Hizmet Veren ile anlaşamamaları durumunda herhangi bir gerek&ccedil;e g&ouml;stermeksizin ve cezai şart &ouml;demeksizin s&ouml;zleşmeden cayma hakkına sahiptir. Hizmet Bedeli iadesi ilgili Hizmet Veren tarafından yapılacak olup uzmanı baksın talep edilemez. Hizmet Alan Web Sitesi &uuml;zerinden Hizmet Talebi&rsquo;ni iptal ederek uzmanı baksın bu durumdan haberdar etmelidir.</p>
<p>17.2. Teklif Modeli&rsquo;nde, uzmanı baksın Hizmet Veren ve Hizmet Alan arasında &ouml;deme, hizmet iptali, indirim veya &uuml;cret iadesi gibi konulara ilişkin doğabilecek anlaşmazlıklarda hi&ccedil;bir sorumluluk kabul etmemektedir.</p>
<p>17.3. Rezervasyon Modeli&rsquo;nde s&ouml;zleşmeden cayma hakkı hizmet başlangı&ccedil; saatinden 24 saat &ouml;ncesine kadar kullanılabilir. Eğer Hizmet Alan&rsquo;ın aktif, s&uuml;resi ge&ccedil;memiş aboneliği var ise ve taahh&uuml;t verdiği s&uuml;re ya da hizmet sayısı bitmeden Abonelik Sistemi&rsquo;nden &ccedil;ıkmak isterse uzmanı baksın tarafından belirlenen Cayma Bedeli&rsquo;ni &ouml;deyerek cayma hakkını kullanabilir. Hizmet Alan Web Sitesi veya mail &uuml;zerinden Hizmet Talebi&rsquo;ni iptal ederek uzmanı baksın&rsquo;i bu durumdan haberdar etmelidir.</p>
<p>17.4. Rezervasyon Modeli&rsquo;nde uzmanı baksın yalnızca aşağıdaki hallerde ilgili &uuml;cretin iadesi i&ccedil;in iş birliği yaptığı &ouml;deme kuruluşuna talimat verecektir:</p>
<p>a) Hizmet Talebi&rsquo;nin veya Anlaşmaya Varılan İş&rsquo;in usul&uuml;ne uygun şartlarda veya m&uuml;cbir sebep hallerine dayalı olarak zorunlu iptali;</p>
<p>b) Hizmet Talebi&rsquo;nin ilgili Hizmet Veren&rsquo;e iletilememesi nedeniyle Hizmet Talebi&rsquo;nin zorunlu iptali;</p>
<p>c) Hizmet Veren&rsquo;in edimi ifa etmemesi sebebiyle veya Rezervasyon&rsquo;un Hizmet Alan tarafından onaylanmasına rağmen 7. Madde&rsquo;deki kurallar dahilinde Kullanıcı talebi &uuml;zerine Rezervasyon&rsquo;un iptali;</p>
<p>d) Hizmet kapsamının Rezervasyon&rsquo;la uyuşmaması nedeniyle hizmetin kısmen veya tamamen zorunlu iptali.</p>
<p>17.5. Online &Ouml;deme Sistemi se&ccedil;eneği dışındaki &ouml;deme vasıtaları ile &ouml;demesi yapılmış Hizmetlerde hizmet bedeli iadesi, Hizmet Veren tarafından doğrudan yapılmaktadır.</p>
<p>Madde 18<br />Hizmet Sorumluluğu, Garanti Verilmemesi ve İlişkinin Bağımsızlığı</p>
<p>18.1. Teklif Modeli&rsquo;nde uzmanı baksın&rsquo;in Hizmet Alan ile Hizmet Veren arasındaki teklif, icap, kabul, s&ouml;zleşme ve &ouml;deme aşamalarında herhangi bir sorumluluğu bulunmamaktadır. uzmanı baksın, Hizmet Alan ve Hizmet Veren arasında uyum olacağını veya Hizmet Alan&rsquo;ın b&ouml;lgesinde, Hizmet Alan&rsquo;ın işini istenen zamanda ve yerde yapmaya muktedir Hizmet Veren bulacağını ya da bulunduracağını garanti etmez. Hizmet Alanlar Hizmet Veren hakkında gerekli araştırmayı kendileri yapmalıdırlar.</p>
<p>18.2. Web Sitesi aracılığı ile Hizmet Verenler&rsquo;den alınacak hizmetlere ilişkin her t&uuml;rl&uuml; sorumluluk Hizmet Verenlere aittir. uzmanı baksın&rsquo;in hi&ccedil;bir sorumluluğu bulunmaz.</p>
<p>18.3. uzmanı baksın, Hizmet Veren'i veya hizmetlerini tasdik veya tavsiye etmez, &ccedil;alışma performansını ya da verilen hizmetlerin sonucu veya kalitesini garanti etmez. uzmanı baksın, &Uuml;ye oylamaları ve &Uuml;ye yorumları gibi sistem i&ccedil;indeki bazı algoritmalar aracılığıyla Hizmet Veren&rsquo;ler arasında bir sıralama, derecelendirme ve kategorilendirme yapabilir, bazı Hizmet Veren&rsquo;leri kullanıcılar tarafından &ccedil;ok&ccedil;a beğenilmiş, tercih/tavsiye edilmiş veya memnun kalınmış olması sebebiyle &ouml;n plana &ccedil;ıkarabilir. Ancak s&ouml;z konusu durum, uzmanı baksın vermiş olduğu bir tasdik veya garanti anlamına gelmemektedir.</p>
<p>18.4. uzmanı baksın, Rezervasyon Modeli&rsquo;nde Hizmet Talebi&rsquo;ni, Hizmet Verenlerin uygunluk durumuna ve Hizmet Talebi&rsquo;nin i&ccedil;eriğine g&ouml;re sisteme kayıtlı Hizmet Profilleri arasından en uygun olan Hizmet Veren profillerine y&ouml;nlendirir ve Hizmet Verenler kendi inisiyatifleri ve se&ccedil;imleri doğrultusunda Hizmet Talebi&rsquo;ni onaylama hakkına sahiptirler. Hizmet Talebi&rsquo;ni hi&ccedil;bir Hizmet Veren&rsquo;in kabul etmemesi durumundan uzmanı baksın sorumlu tutulamaz. uzmanı baksın yalnızca, hizmetlerin belirtilen zamanda ve belirtilen Sabit Fiyat &uuml;zerinden sunulması i&ccedil;in gerekli &ouml;zeni g&ouml;sterecektir.</p>
<p>18.5. uzmanı baksın Hizmet Verenlerin g&uuml;venilirliği, ilgili hizmeti sağlamak i&ccedil;in uygun ve yetkin olduğu, hizmetlerin verilmesi veya zamanında verilmesi, g&uuml;venli ve hatasız olması, hizmet kullanımından elde edilecek sonu&ccedil;ların yeterliliği veya g&uuml;venilirliği veya hizmet kalitesinin beklentilere cevap vermesi gibi konularında hi&ccedil;bir garanti veya taahh&uuml;tte bulunmamaktadır. uzmanı baksın, Rezervasyon Modeli&rsquo;nde yer alan hizmetlere ilişkin olarak yalnızca ilgili Hizmet Verenler ile g&ouml;r&uuml;şme yapmaya &ccedil;alışır ve gerekli g&ouml;rd&uuml;ğ&uuml; durumlarda s&ouml;z konusu Hizmet Veren tarafından sağlanan bilgilerle referans kontrol&uuml; yapmaya &ccedil;alışır. uzmanı baksın tarafından doğrulansa dahi referans kontrolleri bir Hizmet Veren&rsquo;in gelecekteki davranışlarını belirlemez.</p>
<p>18.6. uzmanı baksın, herhangi bir sorumluluğu bulunmamasına rağmen, Hizmet Veren&rsquo;lerin sağladığı hizmetlerin doğru ve tam olarak ifasını sağlamak i&ccedil;in elinden gelen gayreti sarf edecektir. Ancak, Hizmet Veren&rsquo;lerin ağır ihmal veya kusuru nedeniyle Hizmet Alan&rsquo;ları ve 3. kişileri herhangi bir şekilde zarara uğratması ve/veya bu konudaki dava ve takiplerin uzmanı baksın&rsquo;e y&ouml;nelmesi halinde, uzmanı baksın, t&uuml;m zararlar ve ayrıca yargı giderleri, para cezaları ve avukatlık &uuml;cretleri i&ccedil;in Hizmet Veren&rsquo;e r&uuml;cu veyahut uzmanı baksın hak ve alacaklarından takas / mahsup etme hakkını saklı tutmaktadır.</p>
<p>18.7. Rezervasyon Modelinde Hizmet Alan&rsquo;dan veya Hizmet Veren&rsquo;den kaynaklanan hatalardan (yanlış tarih verilmesi, hizmet başlama saatinde Hizmet Alan&rsquo;ın adreste bulunmaması, Hizmet Veren&rsquo;in ilgili tarih ve saatte hizmetin ifası i&ccedil;in gitmemesi, Hizmet Alan&rsquo;ın rezervasyon sırasında belirttiği g&uuml;n ve saat tercihine uygun bir Hizmet Veren bulunamaması vb.) dolayı uzmanı baksın herhangi bir sorumluluğu bulunmamaktadır. uzmanı baksın s&ouml;z konusu durumların oluşmaması i&ccedil;in azami gayreti g&ouml;sterecektir. Ancak oluşan hatalardan veya zararlardan dolayı Hizmet Veren&rsquo;e veya Hizmet Alan&rsquo;a herhangi bir bedel veya tazminat &ouml;demeyecektir.</p>
<p>18.8. uzmanı baksın Hizmet Veren&rsquo;lerin belirlenen tarih ve saatte hizmetin ifası i&ccedil;in Hizmet Alan&rsquo;a anlaşılan işe gitmemesi veya başlamaması durumunda Hizmet Veren&rsquo;e farklı şekillerde yaptırımlar uygulama hakkını saklı tutar. Bu yaptırımlar, Hizmet Veren profilinde değişiklik yapma, profili silme, eksiklik giderilene kadar askıya alma ve Hizmet Veren&rsquo;in Web Sitesi&rsquo;ne tekrar kaydolmasını engelleme ve tazminat talebini kapsayabilir.</p>
<p>18.9. Hizmet Veren tarafından Hizmet Profilinde belirtilen bilgi veya beyanatların doğruluğu Hizmet Veren tarafından taahh&uuml;t edilmektedir, uzmanı baksın&rsquo;in hi&ccedil;bir sorumluluğu bulunmaz.</p>
<p>18.10. Hizmete ilişkin olarak y&uuml;r&uuml;rl&uuml;kteki mevzuat kapsamında temin etmesi gereken her t&uuml;rl&uuml; izin, onay, kontrol belgesi, ruhsat vb. belgeye ilişkin sorumluluk Hizmet Verenlere ait olup, aksi takdirde doğabilecek her t&uuml;rl&uuml; idari, hukuki ve cezai sorumluluk Hizmet Veren&rsquo;e aittir. uzmanı baksın ve 3. kişilerin bu nedenle uğradığı ve/veya uğrayacağı zararlardan sorumluluk ve her t&uuml;rl&uuml; zararın tazmin y&uuml;k&uuml;ml&uuml;l&uuml;ğ&uuml; Hizmet Verenlere aittir.</p>
<p>18.11. uzmanı baksın Hizmet Alan&rsquo;a ulusal, yerel veya diğer resmi dairelerden ya da &uuml;&ccedil;&uuml;nc&uuml; şahıslardan gelen bilginin doğru, hatasız veya g&uuml;ncel olduğunu ya da Hizmet Alan&rsquo;ın s&ouml;z konusu bilgiyi kontrol ettiği tarihte g&uuml;ncel ve akt&uuml;el olduğunu beyan veya taahh&uuml;t etmemektedir.</p>
<p>18.12. Hizmet Veren ile Hizmet Alan arasında yapılacak hizmet s&ouml;zleşmelerinden kaynaklanacak her t&uuml;rl&uuml; vergi, resim, har&ccedil;, &ouml;deme ve benzeri y&uuml;k&uuml;ml&uuml;l&uuml;klerden taraflar doğrudan kendileri sorumludur. uzmanı baksın tarafından işletilen Web Sitesi&rsquo;nde listelenen hizmetler ve &uuml;r&uuml;nlerden dolayı, uzmanı baksın, T&uuml;keticinin Korunması Hakkında Kanun ve ilgili yasal mevzuat kapsamında, satıcı, sağlayıcı, imalat&ccedil;ı, &uuml;retici, bayi, acente, reklamcı veya mecra kuruluşu stat&uuml;s&uuml;nde değildir.</p>
<p>18.13. uzmanı baksın, sisteminde kayıtlı Hizmet Alanların isim, adres ve telefon numarası gibi kişisel verilerinin Teklif oluşturulması veya ilgili hizmetin verilmesine y&ouml;nelik olarak Hizmet Verenler ile paylaşılmasından dolayı Hizmet Alan ve Hizmet Veren(ler) arasında ortaya &ccedil;ıkabilecek sorunlardan veya oluşabilecek zarardan kesinlikle sorumlu değildir. Hizmet Alan ve Hizmet Veren, işbu s&ouml;zleşme kapsamındaki hizmetlerin pazarlanması ve yerine getirilmesi i&ccedil;in kişisel verilerinin işlenmesine ve işbu s&ouml;zleşmedeki ama&ccedil;lara uygun olarak paylaşılmasına muvafakat etmişlerdir. 6698 sayılı Kişisel Verilerin Korunması Kanunu&rsquo;nun 5(c) ve 5(f) maddelerine g&ouml;re, Hizmet Alan ve Hizmet Veren&rsquo;lerin kişisel verilerinin işlenmesi ve sadece s&ouml;zleşme tarafları arasında paylaşılması, a&ccedil;ık rıza alınmasını gerektirmemektedir.</p>
<p>18.14. Hizmet Alan bilgileri uzmanı baksın tarafından Hizmet Veren ile hizmetin sağlanması veya Teklif oluşturulması i&ccedil;in paylaşılmaktadır. Bu bilgi paylaşımı ile hizmetin sorunsuz sağlanması ama&ccedil;lanmaktadır. S&ouml;z konusu bilgilerin Hizmet Veren tarafından ayrıca Hizmet Alan&rsquo;ın onayı alınmadığı hallerde reklam, pazarlama, kişisel vb. herhangi bir durum veya ama&ccedil; i&ccedil;in kullanılması, &uuml;&ccedil;&uuml;nc&uuml; kişilerle paylaşılması veya devri veya Hizmet Alan ile Hizmet Veren(ler) arasında ortaya &ccedil;ıkabilecek sorunlardan veya oluşabilecek zarardan kesinlikle sorumlu değildir.</p>
<p>Madde 19<br />Kullanıcılarla İlişkiler ve İşlemler (T&uuml;m Kullanıcılar)<br />T&Uuml;M KULLANICILARA İLİŞKİN GENEL HAK VE Y&Uuml;K&Uuml;ML&Uuml;L&Uuml;KLER</p>
<p>19.1. Kullanıcılar, birbirleri arasındaki ilişkilerden tamamen kendileri sorumludur.</p>
<p>19.2. Kullanıcı&rsquo;lar birbiriyle ya da uzmanı baksın &ccedil;alışanları ile iletişim kurarken, ırk&ccedil;ı, herhangi bir grup veya kişiye karşı nefret s&ouml;ylemi, kişilik haklarına aykırı, onur kırıcı, hakaret i&ccedil;eren, taciz eden veya tacizi savunan, illegal &amp; ter&ouml;rist faaliyetleri &ouml;ven, haksız rekabet oluşturan, tehdit edici, m&uuml;stehcen, lekeleyici, cinsel taciz oluşturan ve iftiracı nitelikte davranışlar sergileyemez, bu y&ouml;nde i&ccedil;erikler kullanamaz. Aksi bir durum Kullanıcı&rsquo;nın haklarının sona erdirilmesi ve gerektiğinde durumun resmi makamlara bildirilmesini gerektirebilir.</p>
<p>19.3. Gerek Hizmet Veren, gerek Hizmet Alan Kullanıcılar hakkında, hizmetin &ouml;ncesi, hizmetin g&ouml;r&uuml;lmesi ve hizmet sonrasında, herhangi bir su&ccedil; oluşturan davranışlardan dolayı bir soruşturma a&ccedil;ılırsa veya yargılama yapılırsa, uzmanı baksın elindeki t&uuml;m bilgi ve belgeleri talep &uuml;zerine ilgili yargı makamlarıyla paylaşacaktır.</p>
<p>19.4. Hizmet Alan veya Hizmet Veren&rsquo;ler, kendileri veya bir başkası i&ccedil;in hizmet almadığı veya sağlamadığı halde, lehte veya aleyhte yorum yazamaz, bir başkasının iş &uuml;r&uuml;nleri, markası, ticari &uuml;nvanı ve hizmetleri hakkında haksız rekabet yaratacak şekilde i&ccedil;erik yazamaz.</p>
<p>Madde 20<br />Hizmet Alan'ın Y&uuml;k&uuml;ml&uuml;l&uuml;kleri</p>
<p>20.1. Hizmet Alan&rsquo;ın işbu S&ouml;zleşme koşullarına uymaması nedeniyle doğabilecek her t&uuml;rl&uuml; idari, hukuki ve cezai sorumluluk bizzat Hizmet Alan&rsquo;a aittir.</p>
<p>20.2. Teklif Modeli&rsquo;nde Hizmet Alan, Hizmet Talebi i&ccedil;in yalnız bir Teklifi kabul edebilir. Teklifin kabul edilmesi, Hizmet verildiği takdirde Hizmet Veren&rsquo;e &ouml;deme yapmak i&ccedil;in yasal olarak bağlayıcı bir anlaşma yapıldığı anlamına gelir.</p>
<p>20.3. Teklif Modeli&rsquo;nde Hizmet Alan ve Hizmet Veren Teklif &uuml;zerinde anlaştığında, Hizmet Alan aldığı Hizmet karşılığında Hizmet Veren&rsquo;e Teklif&rsquo;te belirtilen tutarı doğrudan &ouml;deyeceğini kabul eder.</p>
<p>20.4. Rezervasyon Modeli'nde Hizmet Alan, Hizmet Veren Hizmet Talebi&rsquo;ni onayladığında verilen hizmetler i&ccedil;in &ouml;ng&ouml;r&uuml;len Sabit Fiyatı Online &Ouml;deme Sistemi ile &ouml;deyeceğini kabul eder.</p>
<p>20.5. Hizmet Alan, Web Sitesi aracılığı ile oluşturulan bir Hizmet Talebi&rsquo;ne ilişkin olarak uzmanı baksın bilgisi dahilinde olmaksızın, uzmanı baksın&rsquo;i dışarıda bırakmak, daha d&uuml;ş&uuml;k bir fiyata anlaşmak veya Komisyon &Uuml;creti &ouml;denmemesi amacıyla Hizmet Veren ile iletişime ge&ccedil;meyecektir.</p>
<p>20.6. Hizmet Alan, Hizmet Veren ile yaptığı s&ouml;zleşmede, uzmanı baksın hi&ccedil;bir şekilde s&ouml;zleşmenin tarafı olmadığını ve sorumluluğu bulunmadığını kabul eder.</p>
<p>20.7. Rezervasyon Modeli&rsquo;nde Hizmet Alan ilgili hizmet tutarının kredi kartından tahsil edilmesini, daha &ouml;nceden paylaşılan kredi kartı bilgilerinin değişmesi durumunda uzmanı baksın bilgilendirmeyi kabul eder.</p>
<p>20.8. Hizmet Alan, kredi kartı bilgilerinin mevzuat kapsamında izin verildiği &ouml;l&ccedil;&uuml;de olmak kaydıyla, uzmanı baksın&rsquo;in anlaşmalı olduğu &ouml;deme kuruluşu sisteminde veya &ldquo;ilk 6 son 4 rakamı&rdquo; ile uzmanı baksın sisteminde saklanması ve sistem işleticileri ile paylaşma yetkisine sahip olduğunu kabul eder. Anlaşmalı &ouml;deme kuruluşu sisteminde oluşabilecek aksaklıklardan uzmanı baksın sorumlu değildir.</p>
<p>20.9. Hizmet Alan, hizmete ilişkin olarak kendisine d&uuml;şen t&uuml;m vergilerden, uzmanı baksın gelirine bağlı oluşan vergiler hari&ccedil; olmak &uuml;zere sorumludur.</p>
<p>20.10. Hizmet Alan, bazı hizmetlerin Hizmet Veren tarafından doğru fiyatlandırma yapılabilmesi i&ccedil;in,, hizmetin g&ouml;r&uuml;leceği veya hizmetin g&ouml;r&uuml;lmesi i&ccedil;in keşif yapılacak yere; Hizmet Veren veya personelinin girişine, keşif i&ccedil;in &ouml;l&ccedil;&uuml; alınmasına veya yerin fotoğraflarının &ccedil;ekilmesine izin vereceğini, bu izin bir başkasına bağlıysa bu izni sağlayacağını kabul eder.</p>
<p>20.11. Bazı hizmetlerin ifa edilebilmesi i&ccedil;in resmi makamlardan veya bina y&ouml;neticilerinden izin alınması gerekebilir. Veya bazı hizmetler, belirli g&uuml;n ve saatlere bağlı olarak ifa edilebilir. Hizmet Alan, gerekli izinleri sağlayacağını ve sadece &ouml;ng&ouml;r&uuml;len g&uuml;n ve saatler i&ccedil;in hizmet alabileceğini kabul eder.</p>
<p>uzmanı baksın sadece kendi hizmet komisyonuyla ilgili olarak Hizmet Alan&rsquo;a fatura kesmek m&uuml;kellefiyetindedir.</p>
<p><br />20.12. Hizmet Alan, hizmeti g&ouml;rd&uuml;receği kafe, restoran, otel ve her t&uuml;rl&uuml; tesiste, iş g&uuml;venliği ve iş sağlığına ilişkin her t&uuml;r &ouml;nlemi almış olmalıdır.</p>
<p>Madde 21<br />Hizmet Veren&rsquo;in Y&uuml;k&uuml;ml&uuml;l&uuml;kleri</p>
<p>21.1. Hizmet Veren&rsquo;in işbu S&ouml;zleşme koşullarına ve Hizmet Alan&rsquo;a karşı &uuml;stlendiği ifa y&uuml;k&uuml;ml&uuml;l&uuml;klerine uymaması nedeniyle doğabilecek her t&uuml;rl&uuml; idari, hukuki ve cezai sorumluluk bizzat Hizmet Veren&rsquo;e aittir.</p>
<p>21.2. Teklif Modeli&rsquo;nde Hizmet Veren&rsquo;in Hizmet Talebi i&ccedil;in verdiği teklif Hizmet Alan tarafından kabul edilebilir. Teklifin kabul edilmesi, Hizmet&rsquo;in Hizmet Veren tarafından anlaşılan zamanda ve yerde yapılacağına dair yasal anlaşma yapıldığı anlamına gelir.</p>
<p>21.3. Rezervasyon Modeli&rsquo;nde Hizmet Veren&rsquo;in Rezervasyonu onaylaması durumunda, Hizmet Talebi&rsquo;nde belirtilen zaman ve yerde hizmetin ifasını ger&ccedil;ekleştireceğini kabul ve beyan eder.</p>
<p>21.4. Hizmet Veren, Web Sitesi aracılığı ile oluşturulan bir Hizmet Talebi&rsquo;ne ilişkin olarak uzmanı baksın&rsquo;in bilgisi dahilinde olmaksızın, uzmanı baksın&rsquo;i dışarıda bırakmak, daha d&uuml;ş&uuml;k bir fiyata anlaşmak veya Komisyon &Uuml;creti &ouml;denmemesi amacıyla Hizmet Alan ile ayrıca bir iletişime ge&ccedil;meyecektir.</p>
<p>21.5. Hizmet Veren, Hizmet Alan ile yaptığı s&ouml;zleşmede, uzmanı baksın&rsquo;in hi&ccedil;bir şekilde s&ouml;zleşmenin tarafı olmadığını ve sorumluluğu bulunmadığını kabul eder.</p>
<p>21.6. Hizmet Veren, kredi kartı bilgilerinin mevzuat kapsamında izin verildiği &ouml;l&ccedil;&uuml;de olmak kaydıyla, uzmanı baksın&rsquo;in anlaşmalı olduğu &ouml;deme kuruluşu sisteminde veya &ldquo;ilk 6 son 4 rakamı&rdquo; ile uzmanı baksın sisteminde saklanması ve sistem işleticileri ile paylaşma yetkisine sahip olduğunu kabul eder. Anlaşmalı &ouml;deme kuruluşu sisteminde oluşabilecek aksaklıklardan uzmanı baksın sorumlu değildir.</p>
<p>21.7. Hizmet Veren&rsquo;in kayıtlı olduğu vergi dairesine bildireceği kazan&ccedil; beyanları, kendisinin yasal sorumluluğunda ve y&uuml;k&uuml;ml&uuml;l&uuml;ğ&uuml;ndedir.</p>
<p>21.8. Hizmet Veren, işin ifası sırasında veya işin ifası i&ccedil;in gerekli iş g&uuml;venliği ve iş sağlığına ilişkin b&uuml;t&uuml;n tedbirleri alacağını, kendisinin ve personelinin bu konuda gerekli eğitimleri aldığını ve bu konudaki sorumlulukların uzmanı baksın&rsquo;e ait olmadığını kabul eder.</p>
<p>Madde 22<br />uzmanı baksın &lsquo;in Yetki ve Y&uuml;k&uuml;ml&uuml;l&uuml;kleri</p>
<p>22.1. uzmanı baksın sistemin &ccedil;alışmasını ge&ccedil;ici bir s&uuml;re askıya alabilir veya tamamen durdurabilir. Kullanıcılar, Web Sitesi'nin kullanımına ilişkin olarak uzmanı baksın &lsquo;e herhangi bir kullanım &uuml;creti &ouml;dememektedirler, s&ouml;z konusu nedenle uzmanı baksın&rsquo;ten sistemin durdurulması veya askıya alınması nedeniyle herhangi bir talepte bulunmayacaklardır.</p>
<p>22.2. uzmanı baksın veya iş birliği yaptığı &ouml;deme kuruluşu g&uuml;venlik ş&uuml;phesi doğuran Hizmet Alan ve Hizmet Veren işlemlerinden dolayı ilgili Kullanıcıların kredi kartı ile online &ouml;deme yapma imk&acirc;nını ge&ccedil;ici bir s&uuml;re askıya alabilir veya tamamen durdurabilir. S&ouml;z konusu nedenle uzmanı baksın&rsquo;in Kullanıcılarına veya 3. kişilere karşı hi&ccedil;bir sorumluluğu bulunmamaktadır.</p>
<p>22.3. Kullanıcılardan Hizmet Veren&rsquo;e ilişkin olarak gelen yorumlar/değerlendirmeler, uzmanı baksın tarafından yapılacak gerekli onay, kontrol ve d&uuml;zeltme akabinde t&uuml;m Kullanıcıların g&ouml;rebileceği şekilde yayınlanır. uzmanı baksın&rsquo;in s&ouml;z konusu yorumları d&uuml;zeltme, sıralama ya da yayımlayıp yayımlamama yetkisi vardır. uzmanı baksın &ouml;nceden haber vererek veya vermeden dilediği zaman Web Sitesi&rsquo;ni (veya bir kısmını) ge&ccedil;ici veya kalıcı olarak değiştirme veya sonlandırma hakkını saklı tutar.</p>
<p>22.4. Hizmet Veren ve Hizmet Alan, Web Sitesi&rsquo;ne y&uuml;klemiş oldukları i&ccedil;eriklerden 5651 sayılı Yasa&rsquo;nın 4. Maddesine g&ouml;re hukuki ve cezai olarak sorumludur. İ&ccedil;eriklerin, uzmanı baksın tarafından yayınlanmış olması Hizmet Veren ve Hizmet Alan&rsquo;ın sorumluluğunu kaldırmamaktadır.</p>
<p>22.5 uzmanı baksın hizmetlerin bazılarını veya tamamını ileride &uuml;cretli veya &uuml;cretsiz yapma hakkını saklı tutar. Bazı hizmetlerin &uuml;cretlendirme ve komisyon politikası satın alınan veya sunulan hizmetlerin sayısı, yoğunluğu veya niceliğine g&ouml;re zaman zaman değişiklik g&ouml;sterebilir.</p>
<p>22.6. uzmanı baksın, dilerse Kullanıcıların e-posta adresini, cep telefon numarasını ve diğer bilgileri doğrulamak amacıyla SMS, e-posta veya diğer teknik ara&ccedil;lar kullanabilir.</p>
<p>22.7. uzmanı baksın &Uuml;yelerin işbu S&ouml;zleşmeyi ihlal ettiğinin tespit edilmesi halinde ya da durumun gerektirdiği &ouml;l&ccedil;&uuml;de hi&ccedil;bir sebep g&ouml;stermek zorunda olmaksızın Web Sitesi&rsquo;ni kullanmaktan ve &Uuml;yelik haklarına erişimden men edebilir, &Uuml;ye&rsquo;liği askıya alabilir, ge&ccedil;ici olarak kullanımı durdurabilir.</p>
<p>22.8. Gelir İdaresi Başkanlığı&rsquo;nca getirilen yasal d&uuml;zenlemeye uygun olarak uzmanı baksın e-fatura ve e-arşiv fatura uygulamalarına ge&ccedil;ilmiştir. E-fatura kullanıcısı olmayan Kullanıcı&rsquo;ların e-arşiv faturaları elektronik ortamda oluşturulacak ve elektronik ortamda muhafaza edilecektir. Elektronik ortamda oluşturulan faturalar ile ilgili bildirim en ge&ccedil; 7 g&uuml;n i&ccedil;erisinde Kullanıcı&rsquo;ların mail adreslerine yapılacak ve faturalar PDF formatında e-posta yolu ile g&ouml;nderilecektir. Elektronik ortamda oluşturulan faturalar, t&uuml;m resmi makam ve merciler nezdinde yasal belge olarak kullanılabilir.</p>
<p>22.9. 24 Aralık 2015 tarihli ve 29572 sayılı Resm&icirc; Gazete&rsquo;de yayınlanan Vergi Usul Kanunu Genel Tebliği&rsquo;ne (Sıra No: 464) g&ouml;re Aracı Hizmet Sağlayıcı olan uzmanı baksın; 01.07.2016 tarihinden itibaren takvim yılının birer aylık s&uuml;releri i&ccedil;erisinde ger&ccedil;ekleşen işlemlere ilişkin olarak; Aracılık hizmetinin sağlandığı internet adres veya adreslerini, Aracılık hizmeti verilen ger&ccedil;ek ya da t&uuml;zel kişilere ait ad soyad/unvan, TCKN/VKN bilgileri ile işyeri adres bilgilerini, Aracılık hizmeti verilenler adına ger&ccedil;ekleştirilen mal ve hizmet satış/kiralama işlemlerine ilişkin her bir tahsilat tutarı ve tarihini, Gelirler İdaresi Başkanlığı&rsquo;nın BTRANS sistemi aracılığıyla elektronik ortamda iletmekle m&uuml;kelleftir.</p>
<p>Madde 23<br />Web Sitesi İ&ccedil;eriği</p>
<p>Y&uuml;r&uuml;rl&uuml;kteki kanunlar uyarınca yasal olarak m&uuml;saade edildiği &ouml;l&ccedil;&uuml;de,<br />23.1. uzmanı baksın Web Sitesinin hatasız, kesintisiz ve g&uuml;venli olacağını ya da Web Sitesinin ya da &uuml;zerindeki herhangi bir i&ccedil;erik, arama veya bağlantının kullanımının belirli sonu&ccedil;lar sağlayacağını taahh&uuml;t etmez.</p>
<p>23.2. uzmanı baksın, Web Sitesinden indirilen herhangi bir dosyanın vir&uuml;s ya da diğer kirli ya da bozucu &ouml;zellikler taşımayacağını garanti edemez.</p>
<p>Madde 24<br />Sorumluluk Sınırlamaları</p>
<p>24.1. Y&uuml;r&uuml;rl&uuml;kteki kanunlar uyarınca yasal olarak m&uuml;saade edildiği s&uuml;rece, uzmanı baksın, Web Sitesi ya da web sitesinin kullanımıyla ilgili olarak, herhangi bir &uuml;&ccedil;&uuml;nc&uuml; şahsın, Web Sitesi kullanıcılarının, reklam verenlerin ve/veya sponsorların fiil, ihmal ve davranışlarına ilişkin sorumlu değildir.</p>
<p>24.2 uzmanı baksın Web Sitesi&rsquo;nin işletiminden veya koşullarının uygulanmasından doğan hi&ccedil;bir veri kaybından sorumlu değildir.</p>
<p>24.3. uzmanı baksın koruma ama&ccedil;lı makul tedbirleri almaktadır. Ancak kendisine ait bilgisayar ağına ve bu ağdaki mevcut veri tabanı bilgilerine yapılabilecek saldırılar sonucu Kullanıcı bilgilerinin k&ouml;t&uuml; ama&ccedil;lı kişilerin eline ge&ccedil;mesi ve bunların k&ouml;t&uuml; niyetli kullanılması halinde doğabilecek sonu&ccedil;lardan dolayı sorumluluk kabul etmez.</p>
<p>24.4. uzmanı baksın 3. kişilerin Web Sitesi&rsquo;nin kullanımı ile ilgili davranışı sonucunda ortaya &ccedil;ıkan, bedensel zarar, duygusal rahatsızlık gibi fakat bunlarla sınırlı olmamak &uuml;zere, doğrudan veya dolaylı, maddi veya manevi her t&uuml;rl&uuml; zararı ve/veya bir Hizmet Veren&rsquo;in verdiği hizmetlerden veya Online &Ouml;deme Sistemi haricinde bir Hizmet Alan&rsquo;ın verilen hizmet karşılığında Hizmet Veren&rsquo;e &ouml;deme yapmamasından dolayı doğabilecek zararlardan sorumluluk kabul etmez.</p>
<p>Madde 25 <br />Telif Hakkı Politikası</p>
<p>25.1. Web Sitesi&rsquo;nde sunulan g&ouml;rsel ve yazılı i&ccedil;erik, kişisel kullanım i&ccedil;indir. uzmanı baksın, Web Sitesi i&ccedil;eriğinde yer alan b&uuml;t&uuml;n alan adı, logo, grafik, ses, ikon, tasarım, metin, imge, html kodu, diğer kodlar, demonstratif, yazılı, elektronik, grafik veya makinede okunabilir şekilde sunulan teknik veriler, uygulanan satış sistemi, iş metodu ve iş modeli de dahil t&uuml;m materyallerin (&ldquo;Materyaller&rdquo;) ve bunlara ilişkin fikri ve sınai m&uuml;lkiyet haklarının sahibi veya lisans sahibidir ve yasal koruma altındadır. Aksi belirtilmedik&ccedil;e ticari ya da kişisel ama&ccedil;larla izinsiz veya kaynak g&ouml;stermeksizin kullanılamaz. Kullanıcı&rsquo;nın kendi resmi ve portf&ouml;y&uuml; hari&ccedil; olmak &uuml;zere, bu sitede yer alan herhangi bir unsuru diğer bir mecrada veya internet sitesinde yayınlaması yasaktır.</p>
<p>25.2. Bu sayfaların tasarımında ve veri tabanı oluşturulmasında kullanılan yazılımın hakkı uzmanı baksın&rsquo;e aittir. Bahsi ge&ccedil;en yazılımın kopyalanması veya kullanılması, kullanılan yazılımların ve teknolojilerin tersine m&uuml;hendislik işlemlerine t&acirc;bi tutulması kesinlikle yasaktır.</p>
<p>25.3. uzmanı baksın&rsquo;e iletilen t&uuml;m yorum ve eleştirilerin telif hakları uzmanı baksın&rsquo;e aittir. uzmanı baksın s&ouml;z konusu yorumlar &uuml;zerinde &ccedil;eşitli değişiklikler yapmak, yorumları silmek veya tamamen kaldırmak hakkını saklı tutar ve yorumların bazılarını yayımlamayabilir. uzmanı baksın kullanım şartları, gizlilik prensipleri ve ge&ccedil;erli yasal d&uuml;zenlemelere bağlı kalmak kaydıyla, kullanıcı hesabına bağlı olan b&uuml;t&uuml;n bilgiler, yorum ve eleştirileri kendi pazarlama faaliyetleri ile ilgili olarak kullanma hakkını saklı tutar.</p>
<p>Madde 26<br />Web Sitesi &Uuml;zerindeki İ&ccedil;erik</p>
<p>26.1. Web Sitesi vasıtasıyla yayınlanan, fikir, tavsiye, a&ccedil;ıklama, inceleme, teklif veya diğer bilgi ya da i&ccedil;erik, ilgili yazarlara aittir. Bahsi ge&ccedil;en i&ccedil;erikten tamamen s&ouml;z konusu yazarlar sorumludur. uzmanı baksın, Web Sitesi &uuml;zerindeki herhangi bir bilginin doğruluğu, b&uuml;t&uuml;nl&uuml;ğ&uuml; veya faydasını garanti etmez veya Web Sitesi &uuml;zerinde g&ouml;sterilen, herhangi bir şahıs&ccedil;a verilmiş fikir, tavsiye veya a&ccedil;ıklamanın doğruluğu veya g&uuml;venilirliğini kabul, tasdik etmez veya sorumluluk kabul etmez.</p>
<p>26.2. Web Sitesi uzmanı baksın kontrol&uuml; altında olmayan başka internet sitelerine bağlantı veya referans i&ccedil;erebilir. uzmanı baksın, bu sitelerin i&ccedil;erikleri veya i&ccedil;erdikleri diğer bağlantılardan sorumlu değildir.</p>
<p>26.3. uzmanı baksın, Web Sitesi &uuml;zerinde yasadışı veya yasak olacak t&uuml;rden i&ccedil;eriği, Web Sitesi&rsquo;nden kaldırma ve s&ouml;z konusu ihlalcilerin &uuml;yeliğini sonlandırma hakkını saklı tutar. Bu h&uuml;k&uuml;m, sayılanlarla sınırlı olmamakla birlikte aşağıdaki t&uuml;rden i&ccedil;eriği kapsar:</p>
<p>&bull; Irk&ccedil;ılık, herhangi bir grup veya kişiye karşı nefret ve fiziksel zararı teşvik eden i&ccedil;erik gibi, diğer Kullanıcıya a&ccedil;ık&ccedil;a saldırıcı nitelikte olan veya hakaret i&ccedil;eren;</p>
<p>&bull; Diğer Kullanıcıyı taciz eden veya tacizi savunan;</p>
<p>&bull; &ldquo;&Ouml;nemsiz posta&rdquo;, &ldquo;zincir mektup&rdquo; veya istenmeyen toplu posta veya &ldquo;spamming&rdquo; iletimi i&ccedil;eren;</p>
<p>&bull; Yanlış veya yanıltıcı olduğunu bildiğiniz bilgileri teşvik eden;</p>
<p>&bull; İllegal faaliyetleri teşvik eden veya başkası hakkında k&ouml;t&uuml;leyici ifadeler kullanan, haksız rekabet oluşturan, tehdit edici, m&uuml;stehcen, lekeleyici ve iftiracı nitelikte davranışları teşvik eden;</p>
<p>&bull; Korsan bilgisayar programları veya linklerin verilmesi, &uuml;retim esnasında konulmuş kopya korumalı cihazları atlatmaya y&ouml;nelik bilgi verilmesi veya korsan resim, ses veya video dosyaları verilmesi veya korsan resim, ses veya video dosyalarına bağlantı verilmesi gibi, başka birinin telifli eserinin yasadışı veya yetkisiz kopyalanmasını teşvik eden;</p>
<p>&bull; Yasaklı veya şifre erişimli sayfalar veya saklı sayfa ya da g&ouml;r&uuml;nt&uuml;ler i&ccedil;eren (başka bir erişilebilir siteden link olarak verilmeyenler);</p>
<p>&bull; 18 yaşın altındaki bireyleri s&ouml;m&uuml;ren cinsel veya şiddet i&ccedil;erikli malzemeler sağlayan veya 18 yaş altındaki bir bireyden kişisel bilgiler talep eden;</p>
<p>&bull; Yasadışı silahların &uuml;retimi veya alımı, başka birinin mahremiyetinin ihlal edilmesi veya bilgisayar vir&uuml;sleri verilmesi veya oluşturulması gibi yasadışı faaliyetler hakkında &ouml;ğretici bilgiler sağlayan;</p>
<p>&bull; Ticari veya kanun dışı ama&ccedil;larla başkalarından şifre veya kişisel tanımlayıcı bilgi talep eden;<br />&bull; &Ouml;nceden yazılı onayımız olmadan yarışmalar, &ccedil;ekilişler, takas, reklam ve saadet zinciri gibi ticari faaliyet ve/veya satışlar i&ccedil;eren;</p>
<p>&bull; Başkalarına ait kişisel bilgileri kayıt eden, yayan, k&ouml;t&uuml;ye kullanan,</p>
<p>&bull; 3. Şahısların marka ve patent gibi, fikri ve sınai haklarını ihlal eden,</p>
<p>&bull; Haksız ticaret uygulamalarına yer veren ve rekabeti sınırlayan, ve</p>
<p>&bull; Ulusal ve/veya yerel t&uuml;ketici koruma kanunlarını ihlal eden.</p>
<p>26.4. Kullanıcı, uzmanı baksın &uuml;zerinde oluşturmuş olduğu profil i&ccedil;eriklerinin &ccedil;eşitli arama motorları tarafından indeksleneceğini, arama sitelerinin arama sonu&ccedil; ekranlarında g&ouml;r&uuml;nt&uuml;lenebileceğini ve &uuml;&ccedil;&uuml;nc&uuml; kişi/kurumlar tarafından g&ouml;r&uuml;leceğini, profilde paylaştığı bilgilerin herhangi bir hukuka aykırılık i&ccedil;ermesi durumunda bizzat kendisinin sorumlu olacağını peşinen kabul eder.</p>
<p>Madde 27<br />Hizmet Alan&rsquo;ların T&uuml;ketici Sıfatıyla Hakları</p>
<p>27.1. Ticari veya mesleki olmayan ama&ccedil;larla hareket eden ger&ccedil;ek veya t&uuml;zel kişi Hizmet Alanlar, 6502 sayılı T&uuml;keticinin Korunması Hakkındaki Kanun gereğince T&uuml;ketici sayılır.</p>
<p>27.2. T&uuml;ketici sıfatına sahip Hizmet Alan, Hizmet Verenin ifa ettiği işler ile ilgili ayıplı mal ve ayıplı hizmet konusunda, Hizmet Veren&rsquo;i muhatap g&ouml;stererek, malın veya hizmetin değerine g&ouml;re T&uuml;ketici Hakem Heyetlerine veya T&uuml;ketici Mahkemelerine başvurabilir. B&ouml;yle bir durumda, uzmanı baksın Hizmet Verene ilişkin iletişim bilgilerini ilgili hakem heyetlerine veya T&uuml;ketici Mahkemelerine sunabilir.</p>
<p>Madde 28<br />Uyuşmazlıkların &Ccedil;&ouml;z&uuml;m&uuml; ve Yetkili Mahkeme</p>
<p>Taraflar, işbu S&ouml;zleşme&rsquo;nin uygulanması ve yorumundan doğacak her t&uuml;rl&uuml; uyuşmazlıkları &ouml;nce kendi aralarında sulh ile &ccedil;&ouml;zmeye &ccedil;alışırlar. Sulhen halledilemeyen uyuşmazlıkların &ccedil;&ouml;z&uuml;m&uuml; i&ccedil;in Antalya Mahkeme ve İcra M&uuml;d&uuml;rl&uuml;kleri&rsquo;nin m&uuml;nhasıran yetkili olduğunu kabul ve beyan ederler.</p>
<p>Madde 29<br />Bilgilerin Saklanması ve Delil S&ouml;zleşmesi</p>
<p>29.1. uzmanı baksın sisteminde kayıtlı kullanıcı bilgileri, teklifleri, yorum/değerlendirmeleri vb. en az &uuml;&ccedil; (3) yıl boyunca saklanır.</p>
<p>29.2. Taraflar bu S&ouml;zleşme&rsquo;den doğabilecek uyuşmazlıklarda uzmanı baksın&rsquo;in ticari defter ve kayıtları ile uzmanı baksın sistemlerinde saklanan verileri her t&uuml;rl&uuml; uyuşmazlıkta 6100 Sayılı HMK&rsquo;nın 193. Maddesi gereği kesin delil kabul edeceğini beyan, kabul ve taahh&uuml;t ederler.</p>
<p>29.3. Herhangi bir uyuşmazlıkta, uyuşmazlık konusu vakıaları ispata elverişli g&ouml;r&uuml;nt&uuml; veya ses kaydı gibi veriler ile elektronik ortamdaki veriler ve bunlara benzer bilgi taşıyıcıları HMK&rsquo;nın 199. Maddesi gereği belge niteliğindedir.</p>
<p>Madde 30<br />S&ouml;zleşmenin İhlali ve Feshi</p>
<p>30.1. Kullanıcıların işbu S&ouml;zleşme h&uuml;k&uuml;mlerine aykırı davranması sonucunda oluşacak durumlarda, kullanıcılar uzmanı baksın&rsquo;in ve 3. Kişilerin uğrayacağı her t&uuml;rl&uuml; zararı karşılamakla sorumludur. uzmanı baksın S&ouml;zleşme&rsquo;nin ihlal edildiğini tespit ettiği takdirde işbu S&ouml;zleşme&rsquo;den doğan talep haklarına halel gelmeksizin işbu S&ouml;zleşmeyi derhal tek taraflı olarak fesih edebilir, s&ouml;zleşmeyi askıya alabilir, ge&ccedil;ici olarak sınırlandırabilir veya diğer yaptırımları uygulayabilir.</p>
<p>30.2. Taraflar işbu S&ouml;zleşme&rsquo;yi diledikleri zaman sona erdirebileceklerdir. S&ouml;zleşme&rsquo;nin feshi anında tarafların birbirlerinden olan alacak hakları etkilenmez.</p>
<p>Madde 31<br />Y&uuml;r&uuml;rl&uuml;k</p>
<p>Bu S&ouml;zleşme Web Sitesi kullanılmaya devam edildiği ve Kullanıcılara uzmanı baksın tarafından yeni bir s&ouml;zleşme sunulmadığı s&uuml;rece y&uuml;r&uuml;rl&uuml;kte kalacaktır.</p>

					</div>
				</div>
			</div>
			
		</div>
	</div>
</div>


<!-- solutech_make_service_area -->
<div class="solutech_make_service_area">
	<div class="container">	
		<div class="row">
			<div class="col-lg-12">
				<div class="witr_section_title white">
					<div class="witr_section_title_inner text-center">
						<h2>uzmanı baksın</h2>		
						<h3>HEMEN KULLANMAYA BAŞLA</h3>		
					</div>
				</div>
				<div class="witr_classic_button_area">
					<!-- btn default style -->
					<div class="witr_btn_style mr tx_op">
						<div class="witr_btn_sinner">	
							<a href="#" class="witr_bbtn bbtn1">APP STORE			
								<span class="btn_w a_active"><i class="icofont-brand-apple"></i>
								</span>
							</a>
							<a href="#" class="witr_btn">GOOGLE PLAY 
									
							<i class="icofont-ui-play"></i>
								</a>	
						</div>						
					</div>
					<!-- btn default style -->
					
					
				</div>
			</div>
		</div>
	</div>
</div>

	
<!-- witrfm_footer_area -->

<?php include 'footer.php' ?>
		



        <!-- Include All JS -->
        <script src="assets/js/vendor/jquery-3.5.1.min.js"></script>
        <script src="assets/js/bootstrap.min.js"></script>
        <script src="assets/js/isotope.pkgd.min.js"></script>
        <script src="assets/js/owl.carousel.min.js"></script>
        <script src="assets/js/jquery.nivo.slider.pack.js"></script>
        <script src="assets/js/slick.min.js"></script>
        <script src="assets/js/imagesloaded.pkgd.min.js"></script>
        <script src="venobox/venobox.min.js"></script>
        <script src="assets/js/jquery.appear.js"></script>
        <script src="assets/js/jquery.knob.js"></script>
        <script src="assets/js/BeerSlider.js"></script>
        <script src="assets/js/theme-pluginjs.js"></script>
        <script src="assets/js/jquery.meanmenu.js"></script>
        <script src="assets/js/ajax-mail.js"></script>		
        <script src="assets/js/theme.js"></script>
	
	</body>
</html>